name: simple-bank

services:
  postgres:
    image: postgres:16.2-alpine3.19
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - DB_SOURCE="postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    depends_on:
      - postgres