version: "3.8"

services:
  simplebank_pg:
    container_name: simplebank_pg
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_simplebank